### PR TITLE
Upgrade phpseclib dependency to version 3.0

### PR DESCRIPTION
**Pull request by Ludo444**
Also upgrade test certificate to generic ssl.com

### CODE REVIEW

**Comment by mlocati** [comment]
I won't add such a breaking change in the near future

**Comment by Ludo444** [comment]
Maybe would be worth to split to new major version? This would go to 2.0, so won't breaking anything that depends on 1.0.

The dependency on phpseclib v2 prevents depending project from using new major features like elliptic curve keys.

**Comment by mlocati** [comment]
> Maybe would be worth to split to new major version?

I don't have time to add more complexity to this project (that is, maintain more than a single branch).

What I'd do instead is maybe something like this:

Add a custom autoloader in composer.json, something like this:
```json
{
    "autoload": {
        "files": ["assets/autoloader.php"]
    }
}
```

Create that `assets/autoloader.php` file with something like this:

```php
<?php

if (class_exists('phpseclib\Math\BigInteger') {
    class_alias(('phpseclib\Math\BigInteger', 'Ocsp\BigInteger');
} elseif (class_exists('phpseclib3\Math\BigInteger') {
    class_alias(('phpseclib3\Math\BigInteger', 'Ocsp\BigInteger');
}
```

And maybe add a stub file, for example `assets/ocsp.php.stub`:
```php
<?php

namepace Ocsp {
    class BigInteger extends \phpseclib\Math\BigInteger {}
}
```

Then I'd use `Ocsp\BigInteger` instead of `phpseclib\Math\BigInteger` or `phpseclib3\Math\BigInteger`.

**Comment by Ludo444** [comment]
What about now? Seems cleaner to me than making `Ocsp\BigInteger` class. If you still prefer it, I can add it.

Also since it's only single class I thought about simply copying BigInteger class file, add necessary license reference (both this and phpseclib use MIT) and remove phpseclib dependency completely.

**Comment by mlocati** [comment]
> What about now? Seems cleaner to me than making `Ocsp\BigInteger` class.

I'm not sure that this approach is so clean: we are making a global class alias, and other libraries may be affected...

**Comment by Ludo444** [comment]
fair point

**Comment by mlocati** [comment]
Sorry for the unexcusable long delay... Superseeded by #10

**Pull request closed without merging**
